// swift-tools-version: 5.9
// MediaNetRenderer — version 0.5.0
//
// RENDERER-ONLY distribution manifest (repo split, >= 0.5.0):
//   - MediaNetAdSDK wrapper releases: https://github.com/media-net/MediaNetAdSDK-dist
//   - OMSDK_Medianet leaf package:    https://github.com/media-net/OMSDK-Medianet-dist
//   - Legacy combined manifests remain frozen on tags v0.3.0–v0.4.7.
// Generated by prebid-renderer-plugin-ios/scripts/release-xcframework.sh —
// do not edit by hand.

import PackageDescription

let package = Package(
    name: "MediaNetRenderer",
    platforms: [
        .iOS(.v13)
    ],
    products: [
        // Standalone core for non-Prebid consumers.
        .library(
            name: "MediaNetRendererCore",
            targets: ["MediaNetRendererCore", "MediaNetRendererDeps"]
        ),
        // Prebid SDK plugin renderer adapter.
        .library(
            name: "MediaNetRendererPrebid",
            targets: ["MediaNetRendererPrebid", "MediaNetRendererCore", "MediaNetRendererDeps"]
        ),
        // MediaNetAdSDK wrapper plugin renderer adapter.
        .library(
            name: "MediaNetRendererAdSDK",
            targets: ["MediaNetRendererAdSDK", "MediaNetRendererCore", "MediaNetRendererAdSDKDeps"]
        ),
        // Umbrella (Core + Prebid) — existing `import MediaNetRenderer` keeps working.
        .library(
            name: "MediaNetRenderer",
            targets: ["MediaNetRendererCore", "MediaNetRendererPrebid", "MediaNetRendererDeps"]
        )
    ],
    dependencies: [
        // Shared dynamic OMID build — single owner of the OMSDK_Medianet target.
        // `from:` (never `exact:`) — cross-package exact pins deadlock graphs.
        .package(
            url: "https://github.com/media-net/OMSDK-Medianet-dist",
            from: "1.5.5"
        ),
        // Wrapper SDK — required by the MediaNetRendererAdSDK flavor's binary.
        .package(
            url: "https://github.com/media-net/MediaNetAdSDK-dist",
            from: "0.4.8"
        )
    ],
    targets: [
        .binaryTarget(
            name: "MediaNetRendererCore",
            url: "https://github.com/media-net/ios-packages/releases/download/v0.5.0/MediaNetRendererCore.xcframework.zip",
            checksum: "5c9c5882f4f3c9ad5ce251b74ad9ef456771407acd41364db98a294619843d3d"
        ),
        .binaryTarget(
            name: "MediaNetRendererPrebid",
            url: "https://github.com/media-net/ios-packages/releases/download/v0.5.0/MediaNetRendererPrebid.xcframework.zip",
            checksum: "1fb9bf25a21361b01b555edef96ca48beaed3a70fe518880f2752ba97766d481"
        ),
        .binaryTarget(
            name: "MediaNetRendererAdSDK",
            url: "https://github.com/media-net/ios-packages/releases/download/v0.5.0/MediaNetRendererAdSDK.xcframework.zip",
            checksum: "69b9168cb788c78b1764d16d058fe962e10fce79b7f8c9b7d4d063663fafb539"
        ),
        // Carries the OMSDK_Medianet package edge (dynamic OMID, embedded once).
        .target(
            name: "MediaNetRendererDeps",
            dependencies: [
                .product(name: "OMSDK_Medianet", package: "omsdk-medianet-dist")
            ],
            path: "Sources/MediaNetRendererDeps"
        ),
        // Carries the OMSDK_Medianet + MediaNetAdSDK package edges for the
        // AdSDK-flavor product.
        .target(
            name: "MediaNetRendererAdSDKDeps",
            dependencies: [
                .product(name: "OMSDK_Medianet", package: "omsdk-medianet-dist"),
                .product(name: "MediaNetAdSDK", package: "medianetadsdk-dist")
            ],
            path: "Sources/MediaNetRendererAdSDKDeps"
        )
    ]
)
